version: 2
updates:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry - checks daily
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "Design System Update"
    allow:
      - dependency-name: "@cmsgov/design-system"
      - dependency-name: "@cmsgov/design-system-docs"
      - dependency-name: "@cmsgov/design-system-scripts"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "Dependencies"
    ignore:
      - dependency-name: "@cmsgov/design-system"
      - dependency-name: "@cmsgov/design-system-docs"
      - dependency-name: "@cmsgov/design-system-scripts"
